# Generated by Django 4.2.7 on 2024-05-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "calendar_id",
                    models.PositiveIntegerField(verbose_name="Calendar ID"),
                ),
                ("date", models.DateField(verbose_name="Date")),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("company_id", models.PositiveIntegerField(verbose_name="Company ID")),
                (
                    "woffu_key",
                    models.CharField(max_length=200, verbose_name="Woffu Key"),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Token"
                    ),
                ),
                (
                    "token_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Token Expiration"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(blank=True, null=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="WoffuUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "woffu_id",
                    models.PositiveIntegerField(unique=True, verbose_name="Woffu ID"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "calendar_id",
                    models.PositiveIntegerField(verbose_name="Calendar ID"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "updated_at",
                    models.DateField(blank=True, null=True, verbose_name="Updated At"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Woffu User",
                "verbose_name_plural": "Woffu Users",
                "unique_together": {("email", "company")},
            },
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("init_date", models.DateField(verbose_name="Init Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "woffu_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.woffuuser",
                        verbose_name="Woffu User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
                "ordering": ["woffu_user", "-init_date"],
            },
        ),
    ]
